export const items = [
    { name: 'Cheese', price: '4.99' },
    { name: 'Bread', price: '2.05' },
    { name: 'Ice cream', price: '3.99' },
    { name: 'Gateau cake', price: '7.99' },
    { name: 'Cholocate drink', price: '2.00' },
    { name: 'Soap', price: '0.99' },
    { name: 'Scissors', price: '1.99' },
    { name: 'School bag', price: '13.99' },
    { name: 'Eraser', price: '0.11' },
    { name: 'Monami D15', price: '2.49' },
    { name: 'Iron Wool', price: '3.59' },
    { name: 'Crepe', price: '2.49' },
    { name: 'Cereal', price: '3.49' },
    { name: 'Bananas', price: '0.69' },
    { name: 'Yogurt', price: '1.99' },
    { name: 'Pasta', price: '2.79' },
    { name: 'Carrots', price: '1.29' },
    { name: 'Apple juice', price: '2.50' },
    { name: 'Avocado', price: '1.99' },
    { name: 'Chicken breast', price: '5.99' },
    { name: 'Green beans', price: '1.99' },
    { name: 'Coffee beans', price: '7.99' },
    { name: 'Toilet paper', price: '0.99' },
    { name: 'Honey', price: '4.49' },
    { name: 'Sour cream', price: '1.49' },
    { name: 'Avocado', price: '1.50' },
    { name: 'Washing machine', price: '399.99' },
    { name: 'Yoga mat', price: '19.99' },
    { name: 'Tennis racket', price: '89.99' },
    { name: 'Bicycle pump', price: '12.99' },
    { name: 'Pineapple', price: '2.99' },
    { name: 'Laptop bag', price: '39.99' },
    { name: 'Sunscreen lotion', price: '8.99' },
    { name: 'Toilet paper', price: '0.99' },
    { name: 'Hand sanitizer', price: '2.99' },
    { name: 'Running shoes', price: '129.99' },
    { name: 'Camping tent', price: '149.99' },
    { name: 'Fruit Basket', price: '9.99' },
    { name: 'Tea Set', price: '18.99' },
    { name: 'Laptop Bag', price: '24.99' },
    { name: 'Candle Set', price: '12.99' },
    { name: 'Vase', price: '8.99' },
    { name: 'Pillow Cover', price: '6.99' },
    { name: 'Curtains', price: '14.99' },
    { name: 'Photo Frame', price: '5.99' },
    { name: 'Wall Clock', price: '10.99' },
    { name: 'Water Bottle', price: '3.99' },
    { name: 'Essential Oils', price: '7.99' },
    { name: 'Hairbrush', price: '2.99' },
    { name: 'Face Mask Set', price: '15.99' },
    { name: 'Sunglasses', price: '12.99' },
    { name: 'Notebook', price: '4.99' },
    { name: 'Backpack', price: '28.99' },
    { name: 'Keychain', price: '1.99' },
    { name: 'Garden Tools Set', price: '19.99' },
    { name: 'Picture Book', price: '7.99' },
    { name: 'Baby Blanket', price: '12.99' },
    { name: 'Earring Set', price: '9.99' },
    { name: 'Yoga Mat', price: '16.99' },
    { name: 'Wireless Charger', price: '22.99' },
    { name: 'Cocktail Shaker', price: '11.99' },
    { name: 'Bluetooth Speaker', price: '36.99' },
    { name: 'Journal', price: '6.99' },
    { name: 'Stuffed Toy', price: '8.99' },
    { name: 'Plant Pot', price: '10.99' },
    { name: 'Hair Dryer', price: '29.99' },
    { name: 'Handheld Fan', price: '7.99' },
    { name: 'Travel Pillow', price: '12.99' },
    { name: 'Puzzle', price: '9.99' },
    { name: 'Cotton Towels Set', price: '18.99' },
    { name: 'Bathrobe', price: '22.99' },
    { name: 'Magnetic Phone Holder', price: '4.99' },
    { name: 'Electric Kettle', price: '32.99' },
    { name: 'Hair Straightener', price: '27.99' },
    { name: 'Aromatherapy Diffuser', price: '21.99' },
    { name: 'Foot Massager', price: '36.99' },
    { name: 'Teapot', price: '13.99' },
    { name: 'Toiletry Bag', price: '16.99' },
    { name: 'Slipper Set', price: '9.99' },
];
